version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: encrypt-app
    container_name: encrypt-app
    restart: always
    environment:
      - DB_NAME=information_security
      - DB_USER=ecrypt
      - DB_PASSWORD=pass@12345
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - spring-network
    links:
      - db:db
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1 --sql_mode=""
    container_name: encryption-db
    restart: always
    networks:
      - spring-network
    ports:
      - '3306:3306'
    volumes:
      - ./data_dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass@12345
      MYSQL_DATABASE: information_security
      MYSQL_USER: ecrypt
      MYSQL_PASSWORD: pass@12345
networks:
  spring-network:
    driver: bridge
